services:

  postgres-server:
    container_name: meucurriculo-postgres-server
    image: 'postgres:18'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - meucurriculo-network

networks:
  meucurriculo-network:
    driver: bridge